/** Free tier daily limits */
export const FREE_DAILY_SWIPES = 5;
export const FREE_DAILY_MESSAGES = 5;

export const STORAGE_KEYS = {
  theme: "bamsignal-theme",
  userProfile: "bamsignal-user-profile",
  datingProfile: "bamsignal-dating-profile",
  matchPreferences: "bamsignal-match-preferences",
  dailySwipes: "bamsignal-daily-swipes",
  dailyMessages: "bamsignal-daily-messages",
  matches: "bamsignal-matches",
  chats: "bamsignal-chats",
  likedBy: "bamsignal-liked-by",
  passed: "bamsignal-passed",
  blocked: "bamsignal-blocked",
  reports: "bamsignal-reports",
  premiumUntil: "bamsignal-premium-until",
  paymentReference: "bamsignal-payment-ref",
  premiumPlans: "bamsignal-premium-plans",
  boostProducts: "bamsignal-boost-products",
  streak: "bamsignal-streak",
  signalsSent: "bamsignal-signals-sent",
  signalsReceived: "bamsignal-signals-received",
  activeBoosts: "bamsignal-active-boosts",
  notifications: "bamsignal-notifications",
  profileViews: "bamsignal-profile-views",
  verificationQueue: "bamsignal-verification-queue",
  cms: "bamsignal-cms",
  analytics: "bamsignal-analytics",
  paymentPending: "bamsignal-payment-pending",
  earlyAccessMember: "bamsignal-early-access",
  foundingMember: "bamsignal-founding-member",
  memberJoinedAt: "bamsignal-member-joined-at",
  discoveryImpressions: "bamsignal-discovery-impressions",
  launchLeads: "bamsignal-launch-leads",
  dailyActiveDays: "bamsignal-daily-active-days",
  firstSignalPromptAt: "bamsignal-first-signal-prompt",
  discoverCityConfig: "bamsignal-discover-city-config",
  quickieUnlockedMatches: "bamsignal-quickie-unlocked-matches",
  authUsernameIndex: "bamsignal-auth-usernames",
  discoverLocationMeta: "bamsignal-discover-location-meta",
  shadowBanned: "bamsignal-shadow-banned"
} as const;
