/** Free tier daily limits */
export const FREE_DAILY_SWIPES = 5;
export const FREE_DAILY_MESSAGES = 5;

export const STORAGE_KEYS = {
  theme: "bamsignal-theme",
  userProfile: "bamsignal-user-profile",
  datingProfile: "bamsignal-dating-profile",
  matchPreferences: "bamsignal-match-preferences",
  dailySwipes: "bamsignal-daily-swipes",
  dailyMessages: "bamsignal-daily-messages",
  matches: "bamsignal-matches",
  chats: "bamsignal-chats",
  likedBy: "bamsignal-liked-by",
  passed: "bamsignal-passed",
  blocked: "bamsignal-blocked",
  reports: "bamsignal-reports",
  premiumUntil: "bamsignal-premium-until",
  paymentReference: "bamsignal-payment-ref",
  paymentKind: "bamsignal-payment-kind",
  paymentBoostId: "bamsignal-payment-boost-id",
  premiumPlans: "bamsignal-premium-plans",
  boostProducts: "bamsignal-boost-products",
  streak: "bamsignal-streak",
  signalsSent: "bamsignal-signals-sent",
  signalsReceived: "bamsignal-signals-received",
  activeBoosts: "bamsignal-active-boosts",
  notifications: "bamsignal-notifications",
  profileViews: "bamsignal-profile-views",
  verificationQueue: "bamsignal-verification-queue",
  cms: "bamsignal-cms",
  analytics: "bamsignal-analytics",
  paymentPending: "bamsignal-payment-pending",
  paymentFlowState: "bamsignal-payment-flow-state",
  paymentCheckoutOpened: "bamsignal-payment-checkout-opened",
  paymentStartedAt: "bamsignal-payment-started-at",
  earlyAccessMember: "bamsignal-early-access",
  foundingMember: "bamsignal-founding-member",
  memberJoinedAt: "bamsignal-member-joined-at",
  discoveryImpressions: "bamsignal-discovery-impressions",
  launchLeads: "bamsignal-launch-leads",
  dailyActiveDays: "bamsignal-daily-active-days",
  firstSignalPromptAt: "bamsignal-first-signal-prompt",
  discoverCityConfig: "bamsignal-discover-city-config",
  quickieUnlockedMatches: "bamsignal-quickie-unlocked-matches",
  quickiePassUntil: "bamsignal-quickie-pass-until",
  profileSocial: "bamsignal-profile-social",
  memberProfileId: "bamsignal-member-profile-id",
  authUsernameIndex: "bamsignal-auth-usernames",
  discoverLocationMeta: "bamsignal-discover-location-meta",
  savedDiscoverProfiles: "bamsignal-saved-discover-profiles",
  shadowBanned: "bamsignal-shadow-banned",
  photoModerationStrikes: "bamsignal-photo-mod-strikes",
  voiceModerationStrikes: "bamsignal-voice-mod-strikes",
  referrals: "bamsignal-referrals",
  launchConfig: "bamsignal-launch-config",
  premiumTrial: "bamsignal-premium-trial",
  firstDayJourney: "bamsignal-first-day-journey",
  discoverShownToday: "bamsignal-discover-shown-today",
  onboardingStep: "bamsignal-onboarding-step",
  spotlightCity: "bamsignal-spotlight-city",
  pendingSignalProfileId: "bamsignal-pending-signal-profile-id",
  pendingSignup: "bamsignal-pending-signup",
  screenshotPrivacyNoticeSeen: "bamsignal-screenshot-privacy-seen",
  savedSearches: "bamsignal-saved-searches",
  subscriptionCatalog: "bamsignal-subscription-catalog",
  premiumBannerDismissedUntil: "bamsignal-premium-banner-dismissed-until"
} as const;
