import {
  QA_AUTOMATED_TEST_SEED,
  QA_CERTIFICATION_APPROVAL_SEED,
  QA_CERTIFICATION_HISTORY_SEED,
  QA_MANUAL_CHECK_SEED,
  QA_RELEASE_GATE_SEED,
  QA_REPORT_SEED,
  QA_SUBSYSTEM_SCORE_SEED
} from "../data/qualityAssuranceCenterSeed";
import type { QAReportTypeId } from "../constants/qualityAssuranceCenter";
import { readJson, writeJson } from "./storage";

const STORAGE_KEY = "bamsignal.qualityAssuranceCenter.v1";

type QualityAssuranceCenterState = {
  subsystemScores: typeof QA_SUBSYSTEM_SCORE_SEED;
  releaseGates: typeof QA_RELEASE_GATE_SEED;
  automatedTests: typeof QA_AUTOMATED_TEST_SEED;
  manualChecks: typeof QA_MANUAL_CHECK_SEED;
  approvals: typeof QA_CERTIFICATION_APPROVAL_SEED;
  history: typeof QA_CERTIFICATION_HISTORY_SEED;
  reports: typeof QA_REPORT_SEED;
  updatedAt: string;
};

function defaultState(): QualityAssuranceCenterState {
  return {
    subsystemScores: [...QA_SUBSYSTEM_SCORE_SEED],
    releaseGates: [...QA_RELEASE_GATE_SEED],
    automatedTests: [...QA_AUTOMATED_TEST_SEED],
    manualChecks: [...QA_MANUAL_CHECK_SEED],
    approvals: [...QA_CERTIFICATION_APPROVAL_SEED],
    history: [...QA_CERTIFICATION_HISTORY_SEED],
    reports: [...QA_REPORT_SEED],
    updatedAt: new Date().toISOString()
  };
}

function loadState(): QualityAssuranceCenterState {
  const stored = readJson<QualityAssuranceCenterState>(STORAGE_KEY, defaultState());
  if (!stored?.subsystemScores?.length) return defaultState();
  return { ...defaultState(), ...stored };
}

function saveState(state: QualityAssuranceCenterState): void {
  writeJson(STORAGE_KEY, { ...state, updatedAt: new Date().toISOString() });
}

export function listQASubsystemScores() {
  return loadState().subsystemScores;
}

export function listQAReleaseGates() {
  return loadState().releaseGates;
}

export function listQAAutomatedTests() {
  return loadState().automatedTests;
}

export function listQAManualChecks() {
  return loadState().manualChecks;
}

export function listQACertificationApprovals() {
  return loadState().approvals;
}

export function listQACertificationHistory() {
  return loadState().history;
}

export function listQAReports() {
  return loadState().reports;
}

export function generateQAReport(reportId: QAReportTypeId, actor: string): string {
  const state = loadState();
  const generatedAt = new Date().toISOString();
  state.reports = state.reports.map((report) =>
    report.id === reportId ? { ...report, lastGeneratedAt: generatedAt } : report
  );
  saveState(state);
  return `${reportId} generated by ${actor} at ${generatedAt}`;
}
