/** Document / ID keyword detection — shared by browser moderation + Node tests. */

export const DOCUMENT_KEYWORD_PATTERNS = [
  /\bnin\b/i,
  /\bnational\s+identification\s+number\b/i,
  /\bfederal\s+republic\s+of\s+nigeria\b/i,
  /\bbvn\b/i,
  /\bbank\s+verification\s+number\b/i,
  /\bpassport\b/i,
  /\bdriver'?s?\s+licen[cs]e\b/i,
  /\bdriving\s+licen[cs]e\b/i,
  /\bpermanent\s+voter'?s?\s+card\b/i,
  /\b(?:pvc|voter'?s?\s+card)\b/i,
  /\bissue\s+date\b/i,
  /\bsurname\b/i,
  /\bgiven\s+names?\b/i,
  /\bcard\s+number\b/i,
  /\bdate\s+of\s+birth\b/i,
  /\bbirth\s+certificate\b/i,
  /\bwaec\b/i,
  /\bwassce\b/i,
  /\bwest\s+african\s+examinations?\s+council\b/i,
  /\bcertificate\s+of\b/i,
  /\butility\s+bill\b/i,
  /\belectricity\s+bill\b/i,
  /\breceipt\b/i,
  /\batm\b/i,
  /\bdebit\s+card\b/i,
  /\bcredit\s+card\b/i,
  /\bidentity\s+card\b/i,
  /\bnational\s+id\b/i,
  /\bslip\b/i,
  /\bembassy\b/i,
  /\bvisa\b/i,
  /\bimmigration\b/i
];

export const IMAGE_URL_PATTERNS = [
  /\bwhatsapp\b/i,
  /\btelegram\b/i,
  /\binstagram\b/i,
  /\btiktok\b/i,
  /\bgmail\b/i,
  /\byahoo\b/i,
  /https?:\/\//i,
  /\bwww\./i,
  /\bwa\.me\b/i,
  /\bt\.me\b/i
];

export const NIGERIAN_PHONE_PATTERNS = [
  /\b0[789][01]\d{8}\b/,
  /\b\+?234[789][01]\d{8}\b/,
  /\b234[789][01]\d{9}\b/
];

export function compactDigits(text) {
  return String(text || "").replace(/\D/g, "");
}

export function containsNigerianPhoneInText(text) {
  const raw = String(text || "");
  if (!raw.trim()) return false;
  if (NIGERIAN_PHONE_PATTERNS.some((pattern) => pattern.test(raw))) return true;
  const compact = compactDigits(raw);
  if (/^0[789][01]\d{8}$/.test(compact)) return true;
  if (/^234[789][01]\d{9}$/.test(compact)) return true;
  return false;
}

export function containsImageUrlLeak(text) {
  const raw = String(text || "");
  if (!raw.trim()) return false;
  return IMAGE_URL_PATTERNS.some((pattern) => pattern.test(raw));
}

/** Explicit URLs/handles in filenames — still block even on messenger auto-names. */
export const EXPLICIT_CONTACT_URL_PATTERNS = [
  /https?:\/\//i,
  /\bwww\./i,
  /\bwa\.me\b/i,
  /\bt\.me\b/i
];

export function containsExplicitContactUrl(text) {
  const raw = String(text || "");
  if (!raw.trim()) return false;
  return EXPLICIT_CONTACT_URL_PATTERNS.some((pattern) => pattern.test(raw));
}

/**
 * Camera roll / messenger / social exports — platform words and long numeric ids
 * in the basename are download metadata, not contact leaks.
 */
export const AUTO_GENERATED_PHOTO_FILENAME_PATTERNS = [
  /^telegram[-_]/i,
  /^whatsapp\s+image/i,
  /^wa\d+/i,
  /^IMG[_\-\s]/i,
  /^IMG-\d+-WA\d+/i,
  /^PXL_/i,
  /^Screenshot/i,
  /^signal-\d/i,
  /^snapchat/i,
  /^Snapchat/i,
  /^FB_IMG/i,
  /^Facebook_/i,
  /^Messenger\b/i,
  /^photo[-_]\d/i,
  /^image[-_]\d/i,
  /^image\s*\(\d+\)/i,
  /^download(\s*\(\d+\))?/i,
  /^DSC[_\-\d]/i,
  /^GOPR\d/i,
  /^mvimg/i,
  /^received_/i,
  /^file[-_]\d/i,
  /^VID[-_]/i,
  /^\d+_\d+_n\./i,
  /^\d{10,}\./i,
  /^-[0-9]+\./i
];

export function basenameOnly(filename) {
  const raw = String(filename || "").trim();
  if (!raw) return "";
  const parts = raw.replace(/\\/g, "/").split("/");
  return parts[parts.length - 1] || "";
}

export function isAutoGeneratedPhotoFilename(filename) {
  const name = basenameOnly(filename);
  if (!name) return false;
  return AUTO_GENERATED_PHOTO_FILENAME_PATTERNS.some((pattern) => pattern.test(name));
}

export function containsDocumentKeywords(text) {
  const raw = String(text || "");
  if (!raw.trim()) return false;
  return DOCUMENT_KEYWORD_PATTERNS.some((pattern) => pattern.test(raw));
}

export function scanPhotoSafetyText(text, { allowDocuments = false } = {}) {
  const raw = String(text || "");
  if (!raw.trim()) {
    return { blocked: false, category: null };
  }

  if (!allowDocuments && containsDocumentKeywords(raw)) {
    return { blocked: true, category: "document_detected" };
  }
  if (containsNigerianPhoneInText(raw)) {
    return { blocked: true, category: "contact_information" };
  }
  if (containsImageUrlLeak(raw)) {
    return { blocked: true, category: "contact_information" };
  }

  return { blocked: false, category: null };
}

/**
 * Filename-only safety — ignores messenger/camera/social export naming conventions.
 * Only blocks Nigerian phone numbers, explicit URLs, and document keywords.
 * Image content (OCR) should use scanPhotoSafetyText instead.
 */
export function scanPhotoFilenameSafetyText(text, { allowDocuments = false } = {}) {
  const name = basenameOnly(text);
  if (!name) {
    return { blocked: false, category: null };
  }

  if (!allowDocuments && containsDocumentKeywords(name)) {
    return { blocked: true, category: "document_detected" };
  }
  if (containsNigerianPhoneInText(name)) {
    return { blocked: true, category: "contact_information" };
  }

  if (isAutoGeneratedPhotoFilename(name)) {
    if (containsExplicitContactUrl(name)) {
      return { blocked: true, category: "contact_information" };
    }
    return { blocked: false, category: null };
  }

  if (containsExplicitContactUrl(name)) {
    return { blocked: true, category: "contact_information" };
  }

  return { blocked: false, category: null };
}
