/** Generated by scripts/build-android-release.mjs — do not edit by hand before release. */
export const BUILD_VERSION = "1.0.13";
export const BUILD_CODE = "16";
export const BUILD_TIME = "2026-06-22T22:10:25.371Z";
export const CACHE_VERSION = "bamsignal-v1.0.13-16-mqprr8bg";
