/** Generated by scripts/build-android-release.mjs — do not edit by hand before release. */
export const BUILD_VERSION = "1.0.15";
export const BUILD_CODE = "18";
export const BUILD_TIME = "2026-06-19T15:00:00.000Z";
export const CACHE_VERSION = "bamsignal-v1.0.15-18";
