/** Generated by scripts/build-android-release.mjs — do not edit by hand before release. */
export const BUILD_VERSION = "1.0.13";
export const BUILD_CODE = "16";
export const BUILD_TIME = "2026-06-19T22:52:05.778Z";
export const CACHE_VERSION = "bamsignal-v1.0.13-16-mqlix9n8";
